config/routes.rb
Rails.application.routes.draw do
  
  root 'restaurants#index'

  devise_for :users

  resources :users, only: [:index, :show]

  # Using the resources helper on line 7 is equivalent to:
  # get 'users', to: 'users#index', as: 'users'
  # get 'users/:id', to: 'users#show', as: 'user'

  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  post 'restaurants/:id', to: 'restaurants#create_review', as: 'create_review'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :restaurant

    validates :content, presence: true
    validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create_review
    restaurant = Restaurant.find(params[:id])
    review = Review.create(review_params)
    review.user = current_user
    review.restaurant = restaurant
    if review.save
      redirect_to restaurant_path(restaurant)
    else
      flash[:error] = review.errors.full_messages.to_sentence
      redirect_to restaurant_path(restaurant)
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="flash alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/layouts/_registration_links.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Welp</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
    <body>
      <nav class="top-bar" data-topbar>
        <div class="top-bar-section">
          <ul class="right">
            <%= render 'layouts/registration_links' %>
            <%= render 'layouts/navigation_links' %>
          </ul>
        </div>
      </nav>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </body>
</html>

app/views/restaurants/index.html.erb
<div class="header">
    <h1> Welp's Restaurants </h1>
</div>

<div class="restaurants">
    <% @restaurants.each do |r| %>
        <div class="row restaurant">
        <h3><%= link_to r.name, restaurant_path(r) %></h3>
        </div>
    <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="large-8 columns">
    <h1><%= @restaurant.name %>'s Reviews</h1>

    <% @restaurant.reviews.each do |r| %>
        <%= link_to r.user.first_name, user_path(r.user) %> says: <%= r.content %> <%= r.rating %>/5
        <br />
    <% end %>

    <br />

    <h4> Post a Review </h4>

    <%= form_for Review.new, url: create_review_path(@restaurant) do |f| %>
        Content: <%= f.text_area :content %>
        <br />
        Rating: <%= f.number_field :rating %>
        <br />
        <%= f.submit %>
    <% end %>

    <br />
    <%= link_to "Back to Home", root_path %>
</div>

app/views/users/index.html.erb
<div class="large-8 columns">
    <h1> Users </h1>

    <% @users.each do |u| %>
        <h2><%= link_to u.first_name, user_path(u) %></h2>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="large-8 columns">
    <h1> <%= @user.first_name %>'s Reviews </h1>

    <% @user.reviews.each do |r| %>
        <b><%= r.created_at %> </b><%= r.content %> @ <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %>
        <br />
    <% end %>
</div>